services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - ./ansible:/ansible
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
        - gitlab-network

networks:
    gitlab-network:
      external: true
